Add `erl_cache_server:purge_all/1` function
alertlogic/erl-cache pull request #13
Opened 2018-06-05 13:38 UTC by danilagamma

This function is useful when we want to purge all the things from specified cache instance.

2018-06-11 14:32 UTC, nalundgaard requested changes
I think that this could be called `evict_all`, and should probably have a public interface in the `erl_cache` module like the `evict/3` function (`evict_all/1,2`). That seems more true to the style of the repo. It looks like there may be a need to ensure that the cache's gen_server stats are updated as well.

2018-06-11 22:43 UTC, danilagamma commented
@nalundgaard updated

2018-06-12 00:10 UTC, nalundgaard approved these changes

2018-06-12 00:10 UTC, nalundgaard commented
Nice! Thanks.

2018-06-12 00:10 UTC, merged