Fix type erl_cache:cache_stat/0
alertlogic/erl-cache pull request #21
Opened 2022-03-15 18:39 UTC by sirikid

2022-03-15 21:35 UTC, nalundgaard requested changes
As long as you're correcting the spec, can you add all of them? see [erl_cache_server.erl#L124](https://github.com/alertlogic/erl-cache/blob/60b344163d3eca9ca633187b309f0251fb2884ed/src/erl_cache_server.erl#L124) and [erl_cache_server.erl#L333-L338](https://github.com/alertlogic/erl-cache/blob/60b344163d3eca9ca633187b309f0251fb2884ed/src/erl_cache_server.erl#L333-L338). looks like it's missing `total_ops` and `set`?

2022-03-16 16:40 UTC, sirikid commented
Sure

2022-03-16 20:16 UTC, nalundgaard approved these changes

2022-03-16 20:19 UTC, merged

2022-03-16 20:33 UTC, nalundgaard commented
Merged and tagged and published an update for this. Thanks for your contribution!